name: autofix.ci

on:
  push:
    branches: [main]
  pull_request: {}
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - run: deno fmt
      - run: deno lint --fix --quiet
        continue-on-error: true
      - uses: autofix-ci/action@v1
