name: checks
on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  format_and_lint:
    runs-on: ubuntu-latest
    name: format and lint
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - run: deno format --check
      - run: deno lint

  tests:
    runs-on: ubuntu-latest
    name: tests
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - run: deno test --junit-path=./junit.xml
      - uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: junit.xml
