name: checks
on:
  push:
    branches: [main]
  pull_request: {}
  workflow_call: {}

jobs:
  format_and_lint:
    runs-on: ubuntu-latest
    name: format and lint
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - run: deno fmt --check
      - run: deno lint --quiet

  tests:
    runs-on: ubuntu-latest
    name: tests
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.INPUTS_PAT }}
      - uses: denoland/setup-deno@v2
      - run: deno test --quiet --allow-read --parallel --coverage=cov/ --junit-path=./junit.xml
      - run: deno coverage --quiet --lcov cov/ > cov.lcov
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - uses: codecov/test-results-action@v1
        if: ${{ !cancelled() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
