name: publish
on:
  workflow_dispatch: {}
  workflow_call:
    inputs:
      ref:
        description: ref to publish
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  jsr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}
      - uses: denoland/setup-deno@v2
      - run: deno publish

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}
      - uses: denoland/setup-deno@v2
      - uses: denoland/deployctl@v1
        with:
          project: aoc-2024
          entrypoint: saas.ts
          root: .
