name: release
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: type of release
        type: choice
        required: true
        default: patch
        options:
          - patch
          - minor
          - major

jobs:
  checks:
    uses: ./.github/workflows/checks.yaml
    permissions:
      checks: write
      pull-requests: write

  release:
    runs-on: ubuntu-latest
    needs: checks
    permissions:
      contents: write
    outputs:
      version: ${{ steps.update-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - run: deno task update:version ${{ github.event.inputs.release-type }}
        id: update-version
      - run: deno fmt
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: release v${{ steps.update-version.outputs.version }}
          tagging_message: v${{ steps.update-version.outputs.version }}

  publish:
    uses: ./.github/workflows/publish.yaml
    needs: release
    with:
      ref: v${{ needs.release.outputs.version }}
    permissions:
      contents: read
      id-token: write
